//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BuildMarketWebServiceSoap")]
    public interface BuildMarketWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProjectInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> SearchProjectInfoAsync(string PrjNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchBiaoDuanInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> SearchBiaoDuanInfoAsync(string ZhongBiaoNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjectInfoOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProjectInfoOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BiaoDuanInfoOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> BiaoDuanInfoOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApplyoverseeOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ApplyoverseeOperationAsync(string XmlDataBaoJian, string BaoJianType, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BeginConstructionOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> BeginConstructionOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConstructLicenceOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ConstructLicenceOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConstructLicModifyOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> ConstructLicModifyOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompleteRegisterOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CompleteRegisterOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompleteRecordOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CompleteRecordOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProgressInfoOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProgressInfoOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QualityAccidentOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> QualityAccidentOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SafetyaccidentOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SafetyaccidentOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToCorrectInfoOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> ToCorrectInfoOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToCorrectFeedbackOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> ToCorrectFeedbackOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WorkingProcedureOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> WorkingProcedureOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JianZhuYueBaoBiaoOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> JianZhuYueBaoBiaoOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QualityMonthlyOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> QualityMonthlyOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QualityAnnalsOperation1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> QualityAnnalsOperation1Async(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QualityAnnalsOperation2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> QualityAnnalsOperation2Async(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjectQSInfoOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> ProjectQSInfoOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjectQSAccountOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> ProjectQSAccountOperationAsync(string XmlData, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PunishMentOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> PunishMentOperationAsync(string XmlData, string XmlDataGx, string XmlDataCon, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BaoJian_serach", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ArrayOfXElement> BaoJian_serachAsync(int PageIndex, int PageSize, string serach, string type, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BaoJian_serach1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ArrayOfXElement> BaoJian_serach1Async(int PageIndex, int PageSize, string serach, string type, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface BuildMarketWebServiceSoapChannel : ServiceReference1.BuildMarketWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class BuildMarketWebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.BuildMarketWebServiceSoap>, ServiceReference1.BuildMarketWebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BuildMarketWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BuildMarketWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), BuildMarketWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BuildMarketWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BuildMarketWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BuildMarketWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BuildMarketWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BuildMarketWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> SearchProjectInfoAsync(string PrjNum)
        {
            return base.Channel.SearchProjectInfoAsync(PrjNum);
        }
        
        public System.Threading.Tasks.Task<bool> SearchBiaoDuanInfoAsync(string ZhongBiaoNum)
        {
            return base.Channel.SearchBiaoDuanInfoAsync(ZhongBiaoNum);
        }
        
        public System.Threading.Tasks.Task<string> ProjectInfoOperationAsync(string XmlData, string type)
        {
            return base.Channel.ProjectInfoOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> BiaoDuanInfoOperationAsync(string XmlData, string type)
        {
            return base.Channel.BiaoDuanInfoOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> ApplyoverseeOperationAsync(string XmlDataBaoJian, string BaoJianType, string Type)
        {
            return base.Channel.ApplyoverseeOperationAsync(XmlDataBaoJian, BaoJianType, Type);
        }
        
        public System.Threading.Tasks.Task<string> BeginConstructionOperationAsync(string XmlData, string type)
        {
            return base.Channel.BeginConstructionOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> ConstructLicenceOperationAsync(string XmlData, string type)
        {
            return base.Channel.ConstructLicenceOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<bool> ConstructLicModifyOperationAsync(string XmlData, string type)
        {
            return base.Channel.ConstructLicModifyOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> CompleteRegisterOperationAsync(string XmlData, string type)
        {
            return base.Channel.CompleteRegisterOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> CompleteRecordOperationAsync(string XmlData, string type)
        {
            return base.Channel.CompleteRecordOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> ProgressInfoOperationAsync(string XmlData, string type)
        {
            return base.Channel.ProgressInfoOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> QualityAccidentOperationAsync(string XmlData, string type)
        {
            return base.Channel.QualityAccidentOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> SafetyaccidentOperationAsync(string XmlData, string type)
        {
            return base.Channel.SafetyaccidentOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<bool> ToCorrectInfoOperationAsync(string XmlData, string type)
        {
            return base.Channel.ToCorrectInfoOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<bool> ToCorrectFeedbackOperationAsync(string XmlData, string type)
        {
            return base.Channel.ToCorrectFeedbackOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> WorkingProcedureOperationAsync(string XmlData, string type)
        {
            return base.Channel.WorkingProcedureOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<bool> JianZhuYueBaoBiaoOperationAsync(string XmlData, string type)
        {
            return base.Channel.JianZhuYueBaoBiaoOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> QualityMonthlyOperationAsync(string XmlData, string type)
        {
            return base.Channel.QualityMonthlyOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> QualityAnnalsOperation1Async(string XmlData, string type)
        {
            return base.Channel.QualityAnnalsOperation1Async(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<string> QualityAnnalsOperation2Async(string XmlData, string type)
        {
            return base.Channel.QualityAnnalsOperation2Async(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<bool> ProjectQSInfoOperationAsync(string XmlData, string type)
        {
            return base.Channel.ProjectQSInfoOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<bool> ProjectQSAccountOperationAsync(string XmlData, string type)
        {
            return base.Channel.ProjectQSAccountOperationAsync(XmlData, type);
        }
        
        public System.Threading.Tasks.Task<bool> PunishMentOperationAsync(string XmlData, string XmlDataGx, string XmlDataCon, string type)
        {
            return base.Channel.PunishMentOperationAsync(XmlData, XmlDataGx, XmlDataCon, type);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ArrayOfXElement> BaoJian_serachAsync(int PageIndex, int PageSize, string serach, string type, string password)
        {
            return base.Channel.BaoJian_serachAsync(PageIndex, PageSize, serach, type, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ArrayOfXElement> BaoJian_serach1Async(int PageIndex, int PageSize, string serach, string type, string password)
        {
            return base.Channel.BaoJian_serach1Async(PageIndex, PageSize, serach, type, password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BuildMarketWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BuildMarketWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BuildMarketWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://sys89.gxzjt.gov.cn:8080/RegisterUser/BuildMarket/WebService/BuildMarketWeb" +
                        "Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BuildMarketWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://sys89.gxzjt.gov.cn:8080/RegisterUser/BuildMarket/WebService/BuildMarketWeb" +
                        "Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BuildMarketWebServiceSoap,
            
            BuildMarketWebServiceSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.2")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
